config/routes.rb
Tracker::Application.routes.draw do
  devise_for :users

  root :to => 'projects#index'

  resources :projects
  resources :tickets

  match '/notice', :to => 'notices#extern'

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :url, :name

  has_many :notices

  def self.find_by_origin origin
    if origin =~ /^http:\/\/(.+)\.(.+)\//
      origin = "#{$1}.#{$2.split('/').first}"
    end
    Project.where(["url LIKE ?", "%#{origin}%"]).first
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :load_projects
  after_filter :add_xhr_response_header

  protect_from_forgery

  private
    def load_projects
      @projects = Project.all
    end

  def add_xhr_response_header
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT'
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  helper_method :project

  before_filter :authenticate_user!

  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: project }
    end
  end

  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: project }
    end
  end

  def edit
  end

  def create
    respond_to do |format|
      if project.save
        format.html { redirect_to project, notice: 'Project was successfully created.' }
        format.json { render json: project, status: :created, location: project }
      else
        format.html { render action: "new" }
        format.json { render json: project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if project.update_attributes(params[:project])
        format.html { redirect_to project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end

  protected
  def project
    if params.has_key?(:id)
      Project.find params[:id]
    else
      Project.new params[:project]
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # TODO redo
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def feedback_snippet(project)
    js = "javascript:(function() {
      var script = document.createElement('script');
      script.type = 'text/javascript';
      script.src = 'http://#{request.host}/assets/client.js?' + (new Date().getTime()) + '&projectId=#{project.id}';
      document.getElementsByTagName('body')[0].appendChild(script);
    }()); return false;
    "
      .gsub(/;\s+/,';')
      .gsub(/\s*=\s*/,'=')
      .gsub(/\s*\+\s*/,'+')
    "<a href='#' onclick=\"#{js}\">Feedback</a>"
  end
end

app/views/layouts/application.html.haml
%html
  %head
    %title BugTracker
    != stylesheet_link_tag 'application.css'
    != javascript_include_tag "application"
    != csrf_meta_tags
%body
  %header
    .container
      .logo BugTracking
      %nav
        %ul.navigation
          - if user_signed_in?
            %li.first!= link_to t(:'navigation.projects'), projects_path
            %li!= link_to t(:'navigation.settings'), edit_user_registration_path
            %li.last!= link_to t(:'navigation.sign_out'), destroy_user_session_path
          - else
            %li.first!= link_to t(:'navigation.sign_in'), user_session_path
            %li.last!= link_to t(:'navigation.sign_up'), new_user_registration_path

  #content
    .container
      // flash notices
      .notice
        != notice
      .alert
        != alert
      != yield
  %footer
    .container

app/views/projects/_form.html.erb
<%= semantic_form_for project do |form| %>
  <%= form.inputs do %>
    <%= form.input :url, :as => 'string' %>
    <%= form.input :name, :as => 'string' %>
  <% end %>
  <%= form.buttons %>
<% end %>

app/views/projects/_form.html.haml
= simple_form_for project do |f|
  .inputs
    = f.input :url
    = f.input :name
  .buttons
    = f.submit

app/views/projects/edit.html.haml
%h1
  = t(:'view.projects.edit.h1')

= render :partial => "form"

app/views/projects/index.html.haml
%h1
	Projekte
	
	
%table
	%tr
		%th
			URL
		%th
			Name
		%th
		%th
		
	- @projects.each do |project|
		%tr
			%td
				= project.url
			%td
				= project.name
			%td
				= link_to 'Show', project
			%td
				= link_to 'Edit', edit_project_path(project)

app/views/projects/new.html.erb
<h1>Projekt erstellen</h1>

<%= render 'form' %>

app/views/projects/new.html.haml
<h1>Projekt erstellen</h1>

<%= render 'form' %>

app/views/projects/show.html.haml
%h1
  Projekt:
  = project.name

%p
  Url:
  = project.url

%p
  Place the following HTML on your project's side to enable Tracker feedback:
%p
  = feedback_snippet project

!= feedback_snippet project